name: Tiny Build
on:
  workflow_dispatch:
concurrency:
  group: "${{ github.workflow }}-${{ github.ref }}"
  cancel-in-progress: true
permissions:
  contents: write
  packages: write
jobs:
  build-armv7-tinygo:
    runs-on: ubuntu-22.04-arm
    steps:
    - name: Prepare & Install dependencies
      run: |
        sudo dpkg --add-architecture armhf
        sudo apt-get update
        DEBIAN_FRONTEND=noninteractive sudo apt-get install -y apt-utils
        DEBIAN_FRONTEND=noninteractive sudo apt-get install -y \
          gcc-arm-linux-gnueabihf
          
    - uses: actions/checkout@v5

    # --- Set build environment variables ---
    - name: Set build environment
      run: |
        echo "BUILDTIME=$(TZ=Asia/Jakarta date)" >> $GITHUB_ENV
        echo "CGO_ENABLED=0" >> $GITHUB_ENV
        # echo "BUILDTAG=-extldflags --static" >> $GITHUB_ENV
        echo "GOTOOLCHAIN=local" >> $GITHUB_ENV
        VERSION="${GITHUB_REF_NAME,,}-$(git rev-parse --short HEAD)"
        echo "VERSION=${VERSION}" >> $GITHUB_ENV
    - name: Setup Go
      uses: actions/setup-go@v5
      with:
        go-version: 1.23
        
    - name: Setup TinyGo
      uses: acifani/setup-tinygo@v2
      with:
        tinygo-version: '0.40.1'
        install-binaryen: false

    # --- Build with TinyGo ---
    - name: Build mihomo (TinyGo Linux ARMv7)
      env:
        GOOS: linux
        GOARCH: arm
      run: |
        tinygo version
        tinygo build -o mihomo-armv7 \
          -tags "with_gvisor" \
          -ldflags "${BUILDTAG} -X github.com/metacubex/mihomo/constant.Version=${VERSION} -X github.com/metacubex/mihomo/constant.BuildTime=${BUILDTIME} -w -s"

    # --- Compress artifact to .gz ---
    - name: Compress artifact
      run: |
        gzip -c mihomo-armv7 > smartclash-tiny-linux-armv7-${VERSION}.gz

    # --- Upload artifact ---
    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: smartclash-tiny-linux-armv7
        path: smartclash-tiny-linux-armv7-${VERSION}.gz
